### ISSUE TITLE
Mod causes game crash with exit code 225

### ISSUE THREAD

**Issue by EldestEuryale** [Skylortrexler/Difficultyplus#6]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2022-09-12 10:22:03
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'difficultyplus'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: website/skylorbeck/minecraft/skylorlib/MidnightConfig
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at website.skylorbeck.minecraft.difficultyplus.Difficultyplus.onInitialize(Difficultyplus.java:15)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: website.skylorbeck.minecraft.skylorlib.MidnightConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.18.10-76051810-generic
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1029549216 bytes (981 MiB) / 1744830464 bytes (1664 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: GA104 [GeForce RTX 3070 Lite Hash Rate]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2488
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12064.70
	Virtual memory used (MB): 7547.13
	Swap memory total (MB): 4095.49
	Swap memory used (MB): 1.00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		difficultyplus: Difficulty Plus 1.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Sourpunch14** [comment]
I'm assuming you got the mod from Modrinth? It seems like the page is missing any mention of a dependancy for skylib if you don't have it already

**Comment by skylorbeck** [comment]
> I'm assuming you got the mod from Modrinth? It seems like the page is missing any mention of a dependancy for skylib if you don't have it already

It's listed now. Changed it this morning after I saw the other one.
